### ISSUE TITLE
Add twig variable inside content ?

### ISSUE THREAD

**Issue by ibasaw** [symfony-cmf/content-bundle#149]
how to use a twig variable inside the content ?

Even with raw attribute on the body: {{ createphp_content(rdf.body)|raw }} doens't help

the variable is rendered like this {{ var }}

**Comment by dbu** [comment]
sorry, i missed this issue. can you show a full fragment of your template? and are you saying the twig template outputs curly brackets instead of evaluating the expression inside the brackets?

**Comment by ibasaw** [comment]
```
{% extends 'SyliusWebBundle:Frontend:layout.html.twig' %}

{% if cmfMainContent is not defined %}
    {% set cmfMainContent = static_content %}
{% endif %}

{% block head %}
    {% createphp cmfMainContent as='rdf' noautotag %}
        <title>{{ createphp_content(rdf.metaTitle) }}</title>
        <meta name="description" content="{{ createphp_content(rdf.metaDescription) }}" />
        <meta name="keywords" content="{{ createphp_content(rdf.metaKeywords) }}" />
    {% endcreatephp %}
{% endblock %}

{% block content %}
{% createphp cmfMainContent as='rdf' noautotag %}
<div {{ createphp_attributes(rdf) }}>
    <!-- BREADCRUMBS -->
    <section class="page-section breadcrumbs">
        <div class="container">
            <div class="page-header">
                <h1 {{ createphp_attributes(rdf.title) }}>{{ createphp_content(rdf.title) }}</h1>
            </div>
            <ul class="breadcrumb"></ul>
        </div>
    </section>
    <!-- /BREADCRUMBS -->

    <!-- PAGE -->
    <section class="page-section color">
        <div class="container">
            <div {{ createphp_attributes(rdf.body) }}>{{ createphp_content(rdf.body)|raw }}</div>
        </div>
    </section>
    <!-- /PAGE -->
</div>
{% endcreatephp %}
{% endblock %}
```


example of the html view rendered

```
Le remboursement sera effectué au plus tard dans les 72 heures suivant la réception de votre colis soit par carte bancaire, soit par paypal, en fonction du mode de paiement de votre commande. 

{{url}}
```

**Comment by dbu** [comment]
if i get it correctly, you want to evaluate twig for the content of e.g. rdf.body? this would not be something that is provided by this bundle. 

uncontrolled twig evaluation of content would require full trust in your content editors. and even then, the editors could break the page by writing syntax errors. if you can live with those risks, there is a twig function that seems to do this: http://twig.sensiolabs.org/doc/functions/template_from_string.html - you could experiment with that.

**Comment by wouterj** [comment]
Closing as this is not related to this bundle. I would again repeat that allowing this is quite a trustfull situation.

What you can do is implement a custom Twig function/tag that would only parse `{{ varname }}` and replace it with the value of the variable. See http://symfony.com/doc/current/templating/twig_extension

**Comment by dbu** [comment]
as an example, we do that with the cmf blocks btw. you can embed blocks
into content without the security risks of full twig by editors.

http://symfony.com/doc/current/cmf/bundles/block/introduction.html#embedding-blocks-in-wysiwyg-content

the implementation is in CmfBlockHelper and EmbedBlocksParser
https://github.com/symfony-cmf/block-bundle/tree/master/Templating/Helper

**Comment by ibasaw** [comment]
i did the twig function as mention wouterj. 

i replaced all my twig globals keys by their string values. 

Problem solved, thank you !
