### ISSUE TITLE
form type guesser for ckeditor

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/content-bundle#171]
we could add a type guesser for ckeditor here. the tricky bit would be to decide where a single line text is better, where plain text and where wysiwyg.

**Comment by ElectricMaxxx** [comment]
This should go into `SontataDoctrinePhpcrAdminBundle`, right?

**Comment by dbu** [comment]
not sure what i meant originally. but either way as phpcr-odm has no distinction between varchar and long text, i think such a guesser would do more harm than good. we can't reliably figure out if the dev rather wants a plain text field or a textarea/wysiwyg.
